import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "react-tooltip/dist/react-tooltip.css";
import "./globals.css";
import NextUIProviderIndex from "@/layout/NextUIProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className=" font-IranYekanNumber" dir="rtl" lang="en">
      <head>
        <link rel="icon" href="/next.svg" sizes="any" />
        <title>admin</title>
      </head>
      <body className="bg-[#F9FAFB] min-h-screen">
        <NextUIProviderIndex>{children}</NextUIProviderIndex>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
